-- MySQL Script generated by MySQL Workbench
--  4.11.2020 (ср) 11:24:07 EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quiz` DEFAULT CHARACTER SET utf8 ;
USE `quiz` ;

-- -----------------------------------------------------
-- Table `quiz`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `registerDate` DATETIME NULL,
  `avatar` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roleID` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleID`)
    REFERENCES `quiz`.`roles` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `category_UNIQUE` (`category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`quizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`quizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `time` INT NULL,
  `teacherID` INT NOT NULL,
  `categoryID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quizes_users1_idx` (`teacherID` ASC),
  INDEX `fk_quizes_categories1_idx` (`categoryID` ASC),
  CONSTRAINT `fk_quizes_users1`
    FOREIGN KEY (`teacherID`)
    REFERENCES `quiz`.`users` (`id`),
  CONSTRAINT `fk_quizes_categories1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `quiz`.`categories` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `quizID` INT NOT NULL,
  `started` DATETIME NULL,
  `finished` DATETIME NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_history_users1_idx` (`userID` ASC),
  INDEX `fk_history_quizes1_idx` (`quizID` ASC),
  CONSTRAINT `fk_history_users1`
    FOREIGN KEY (`userID`)
    REFERENCES `quiz`.`users` (`id`),
  CONSTRAINT `fk_history_quizes1`
    FOREIGN KEY (`quizID`)
    REFERENCES `quiz`.`quizes` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quizID` INT NOT NULL,
  `points` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_quizes1_idx` (`quizID` ASC),
  CONSTRAINT `fk_questions_quizes1`
    FOREIGN KEY (`quizID`)
    REFERENCES `quiz`.`quizes` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quiz`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questionID` INT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `isTrue` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answers_questions1_idx` (`questionID` ASC),
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questionID`)
    REFERENCES `quiz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
