const SET_LEADERBOARD = 'SET_LEADERBOARD';
const SET_LEADERBOARD_PAGE = 'SET_LEADERBOARD_PAGE';
const FETCH_LEADERBOARD_FAILED = 'FETCH_LEADERBOARD_FAILED';
const START_LOADING_LEADERBOARD = 'START_LOADING_LEADERBOARD';
const STOP_LOADING_LEADERBOARD = 'STOP_LOADING_LEADERBOARD';

const CREATE_QUIZ_COMPLETED = 'CREATE_QUIZ_COMPLETED';
const CREATE_QUIZ_FAILED = 'CREATE_QUIZ_FAILED';
const CLEAR_LAST_CREATED_QUIZ = 'CLEAR_LAST_CREATED_QUIZ';

const SET_STUDENT_HISTORY = 'SET_STUDENT_HISTORY';
const SET_STUDENT_HISTORY_PAGE = 'SET_STUDENT_HISTORY_PAGE';
const SET_SOLVING_INFO = 'SET_SOLVING_INFO';
// const SET_FINISH_SOLVING_INFO = 'SET_FINISH_SOLVING_INFO';
const FETCH_STUDENT_HISTORY_FAILED = 'FETCH_STUDENT_HISTORY_FAILED';
const START_LOADING_STUDENT_HISTORY = 'START_LOADING_STUDENT_HISTORY';
const STOP_LOADING_STUDENT_HISTORY = 'STOP_LOADING_STUDENT_HISTORY';

const SET_CATEGORIES = 'SET_CATEGORIES';
const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';
const STOP_LOADING_CATEGORIES = 'STOP_LOADING_CATEGORIES';

const TEACHER_DASH_GET_QUIZZES_LOADING = 'TEACHER_DASH_GET_QUIZZES_LOADING';
const TEACHER_DASH_GET_QUIZZES_COMPLETED = 'TEACHER_DASH_GET_QUIZZES_COMPLETED';
const TEACHER_DASH_GET_QUIZZES_FAILED = 'TEACHER_DASH_GET_QUIZZES_FAILED';
const TEACHER_DASH_CREATE_CATEGORY_COMPLETED = 'TEACHER_DASH_CREATE_CATEGORY_COMPLETED';
const TEACHER_DASH_CREATE_CATEGORY_FAILED = 'TEACHER_DASH_CREATE_CATEGORY_FAILED';

const SET_QUIZZES = 'SET_QUIZZES';
const FETCH_QUIZZES_FAILED = 'FETCH_QUIZZES_FAILED';
const START_LOADING_QUIZZES = 'START_LOADING_QUIZZES';
const STOP_LOADING_QUIZZES = 'STOP_LOADING_QUIZZES';

const FETCH_QUIZ_TAKEN_HISTORY_COMPLETED = 'FETCH_QUIZ_TAKEN_HISTORY_COMPLETED';
const FETCH_QUIZ_TAKEN_HISTORY_FAILED = 'FETCH_QUIZ_TAKEN_HISTORY_FAILED';

export {
  SET_LEADERBOARD,
  SET_LEADERBOARD_PAGE,
  FETCH_LEADERBOARD_FAILED,
  START_LOADING_LEADERBOARD,
  STOP_LOADING_LEADERBOARD,
  SET_STUDENT_HISTORY,
  SET_STUDENT_HISTORY_PAGE,
  SET_SOLVING_INFO,
  FETCH_STUDENT_HISTORY_FAILED,
  START_LOADING_STUDENT_HISTORY,
  STOP_LOADING_STUDENT_HISTORY,
  SET_CATEGORIES,
  FETCH_CATEGORIES_FAILED,
  START_LOADING_CATEGORIES,
  STOP_LOADING_CATEGORIES,
  TEACHER_DASH_GET_QUIZZES_LOADING,
  TEACHER_DASH_GET_QUIZZES_COMPLETED,
  TEACHER_DASH_GET_QUIZZES_FAILED,
  TEACHER_DASH_CREATE_CATEGORY_COMPLETED,
  TEACHER_DASH_CREATE_CATEGORY_FAILED,
  CREATE_QUIZ_COMPLETED,
  CREATE_QUIZ_FAILED,
  CLEAR_LAST_CREATED_QUIZ,
  SET_QUIZZES,
  FETCH_QUIZZES_FAILED,
  START_LOADING_QUIZZES,
  STOP_LOADING_QUIZZES,
  FETCH_QUIZ_TAKEN_HISTORY_COMPLETED,
  FETCH_QUIZ_TAKEN_HISTORY_FAILED,

};
