const SET_LEADERBOARD = 'SET_LEADERBOARD';
const SET_LEADERBOARD_PAGE = 'SET_LEADERBOARD_PAGE';
const FETCH_LEADERBOARD_FAILED = 'FETCH_LEADERBOARD_FAILED';
const START_LOADING_LEADERBOARD = 'START_LOADING_LEADERBOARD';
const STOP_LOADING_LEADERBOARD = 'STOP_LOADING_LEADERBOARD';

const CREATE_QUIZ_COMPLETED = 'CREATE_QUIZ_COMPLETED';
const CREATE_QUIZ_FAILED = 'CREATE_QUIZ_FAILED';
const CLEAR_LAST_CREATED_QUIZ = 'CLEAR_LAST_CREATED_QUIZ';

const SET_STUDENT_HISTORY = 'SET_STUDENT_HISTORY';
const SET_STUDENT_HISTORY_PAGE = 'SET_STUDENT_HISTORY_PAGE';
const FETCH_STUDENT_HISTORY_FAILED = 'FETCH_STUDENT_HISTORY_FAILED';
const START_LOADING_STUDENT_HISTORY = 'START_LOADING_STUDENT_HISTORY';
const STOP_LOADING_STUDENT_HISTORY = 'STOP_LOADING_STUDENT_HISTORY';

const SET_CATEGORIES = 'SET_CATEGORIES';
const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';
const STOP_LOADING_CATEGORIES = 'STOP_LOADING_CATEGORIES';

const SET_QUIZES = 'SET_QUIZES';
const FETCH_QUIZES_FAILED = 'FETCH_QUIZES_FAILED';
const START_LOADING_QUIZES = 'START_LOADING_QUIZES';
const STOP_LOADING_QUIZES = 'STOP_LOADING_QUIZES';

export {
  SET_LEADERBOARD,
  SET_LEADERBOARD_PAGE,
  FETCH_LEADERBOARD_FAILED,
  START_LOADING_LEADERBOARD,
  STOP_LOADING_LEADERBOARD,
  SET_STUDENT_HISTORY,
  SET_STUDENT_HISTORY_PAGE,
  FETCH_STUDENT_HISTORY_FAILED,
  START_LOADING_STUDENT_HISTORY,
  STOP_LOADING_STUDENT_HISTORY,
  SET_CATEGORIES,
  FETCH_CATEGORIES_FAILED,
  START_LOADING_CATEGORIES,
  STOP_LOADING_CATEGORIES,
  CREATE_QUIZ_COMPLETED,
  CREATE_QUIZ_FAILED,
  CLEAR_LAST_CREATED_QUIZ,
  SET_QUIZES,
  FETCH_QUIZES_FAILED,
  START_LOADING_QUIZES,
  STOP_LOADING_QUIZES,
};
