const SET_LEADERBOARD = 'SET_LEADERBOARD';
const FETCH_LEADERBOARD_FAILED = 'FETCH_LEADERBOARD_FAILED';
const START_LOADING_LEADERBOARD = 'START_LOADING_LEADERBOARD';
const STOP_LOADING_LEADERBOARD = 'STOP_LOADING_LEADERBOARD';

const SET_STUDENT_HISTORY = 'SET_STUDENT_HISTORY';
const FETCH_STUDENT_HISTORY_FAILED = 'FETCH_STUDENT_HISTORY_FAILED';
const START_LOADING_STUDENT_HISTORY = 'START_LOADING_STUDENT_HISTORY';
const STOP_LOADING_STUDENT_HISTORY = 'STOP_LOADING_STUDENT_HISTORY';


const SET_CATEGORIES = 'SET_CATEGORIES';
const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
const START_LOADING_CATEGORIES = 'START_LOADING_CATEGORIES';
const STOP_LOADING_CATEGORIES = 'STOP_LOADING_CATEGORIES';

const SET_QUIZES = 'SET_QUIZES';
const FETCH_QUIZES_FAILED = 'FETCH_QUIZES_FAILED';
const START_LOADING_QUIZES = 'START_LOADING_QUIZES';
const STOP_LOADING_QUIZES = 'STOP_LOADING_QUIZES';

export {
  SET_LEADERBOARD,
  FETCH_LEADERBOARD_FAILED,
  START_LOADING_LEADERBOARD,
  STOP_LOADING_LEADERBOARD,
  SET_STUDENT_HISTORY,
  FETCH_STUDENT_HISTORY_FAILED,
  START_LOADING_STUDENT_HISTORY,
  STOP_LOADING_STUDENT_HISTORY,
  SET_CATEGORIES,
  FETCH_CATEGORIES_FAILED,
  START_LOADING_CATEGORIES,
  STOP_LOADING_CATEGORIES,
  SET_QUIZES,
  FETCH_QUIZES_FAILED,
  START_LOADING_QUIZES,
  STOP_LOADING_QUIZES,
};
